# Generated by Django 5.2.6 on 2025-10-08 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('Mon, 7 Oct - 5 PM', 'Mon, 7 Oct - 5 PM'), ('Wed, 9 Oct - 3 PM', 'Wed, 9 Oct - 3 PM'), ('Fri, 11 Oct - 4 PM', 'Fri, 11 Oct - 4 PM')], max_length=50)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
